#!/bin/bash
#
#  curl commands to reload the data
#
#

set -e

# # Set enviroment from .env file
# setEnviroment () {
# 	export $(cat .env | grep "#" -v)
# }

# setEnviroment

printf "⏳ Provisioning IoT devices "

# ####################################################
# #
# # Create a Service Groups for all OPC-UA IoT devices
##

# curl -s -o /dev/null -X POST \
#   "http://iot-agent:4041/iot/services" \
#   -H 'Content-Type: application/json' \
#   -H 'fiware-service: opcua_car' \
#   -H 'fiware-servicepath: /demo' \
#   -d '{
#  "services": [
#    {
#      "apikey":      "1068318794",
#      "cbroker":     "http://orion:1026",
#      "entity_type": "Device",
#      "resource":    "/iot/d"    
#    }
#  ]
# }'

# "entity_type": "PLC",

# ####################################################
# #
# # Provision devices for Orion
# #

## Area
curl -iX POST \
  'http://orion:1026/v2/entities' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: opcua_car' \
  -H 'fiware-servicepath: /demo' \
  -d '
{
	"type": "Area",
	"id": "urn:ngsiv2:I40Asset:Area:001"
}'

## Workstation
curl -iX POST \
  'http://orion:1026/v2/entities' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: opcua_car' \
  -H 'fiware-servicepath: /demo' \
  -d '
{
	"type": "Workstation",
	"id": "urn:ngsiv2:I40Asset:Workstation:001"
}'

# ## PLC - Should be already provisioned by the IoT Agent

# curl -iX POST \
#   'http://orion:1026/v2/entities' \
#   -H 'fiware-service: opcua_car' \
#   -H 'fiware-servicepath: /demo' \
#   -H 'Content-Type: application/json' \
#   -d '
# {
# 	"type": "PLC",
# 	"id": "urn:ngsiv2:I40Asset:PLC:001"
# }'

## PLC - Add OEE attributes
curl -iX POST \
  'http://orion:1026/v2/entities/urn:ngsiv2:I40Asset:PLC:001/attrs' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: opcua_car' \
  -H 'fiware-servicepath: /demo' \
  -d '{
	"Availability": {
		"type": "Float",
		"value": null
	},
	"Performance": {
		"type": "Float",
		"value": null
	},
	"Quality": {
		"type": "Float",
		"value": null
	},
	"OEE": {
		"type": "Float",
		"value": null
	}
}'


# ####################################################
# #
# # Provision Relationship
# #

## Workstation hasParent Area
curl -iX POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: opcua_car' \
  -H 'fiware-servicepath: /demo' \
  -d '{
  "actionType": "APPEND",
  "entities": [
    {
      "id": "urn:ngsiv2:I40Asset:Workstation:001",
      "type": "PLC",
      "hasParentI40Asset": {
        "type": "Relationship",
        "value": "urn:ngsiv2:I40Asset:Area:001"
      }
    }
  ]
}'

## PLC hasParent Workstation
curl -iX POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: opcua_car' \
  -H 'fiware-servicepath: /demo' \
  -d '{
  "actionType": "APPEND",
  "entities": [
    {
      "id": "urn:ngsiv2:I40Asset:PLC:001",
      "type": "PLC",
      "hasParentI40Asset": {
        "type": "Relationship",
        "value": "urn:ngsiv2:I40Asset:Workstation:001"
      }
    }
  ]
}'


# ####################################################
# #
# # Provision subscriptions for QuantumLeap
# #

curl -s -o /dev/null -X POST \
	'http://orion:1026/v2/subscriptions/' \
	-H 'Content-Type: application/json' \
	-H 'fiware-service: opcua_car' \
	-H 'fiware-servicepath: /demo' \
	-d '{
	"description": "Provision subscriptions for QuantumLeap",
	"subject": {
		"entities": [
			{
				"idPattern": ".*",
				"type": "PLC"
			}
		],
		"condition": {
			"attrs": ["processStatus"]
		}
	},
	"notification": {
		"http": {
			"url": "http://quantumleap:8668/v2/notify"
		},
		"attrs": ["processStatus"],
		"metadata": ["dateCreated", "dateModified"]
	},
	"throttling": 1
}'


# ####################################################
# #
# # Provision Sensors
# #


echo -e " \033[1;32mdone\033[0m"