  superset:
    # image: apache/superset:latest
    image: apache/superset:bc435e08d01b87efcf8774f29a7078cee8988e39
    container_name: superset
    depends_on:
      - crate-db
    ports:
      - "${SUPERSET_PORT}:8088"
    volumes:
    - superset:/var/lib/superset
    # command: create-admin --username admin --password admin --firstname Superset --lastname Admin --email admin@superset.com